clc;
close all;
clear all;
num=input('enter the numerator coefficients :');
den=input('enter the denominator coefficients :');
[h,om]=freqz(num,den);
disp(h);
subplot(2,1,1);
plot(om/pi,20*log10(abs(h)));
disp(abs(h));
xlabel('normalized frequency');
ylabel('gain in db');
title('magnitude response');
subplot(2,1,2);
plot(om/pi,angle(h));
disp(angle(h));
xlabel('normalized frequency');
ylabel('angle of h');
title('phase response');